# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebcf9f0d1768a9f9c1c97cabd31162637b3427f550ff50a3ede335192012e476077ceae8482c0a967d7202639617f4ebc380b0703d102d6d36547069b8e40067

test:
  secret_key_base: 51079ad29b485989fc6f662eda5ff1ac7af7f7843bba862a27fe339f504fa2a17b64c67a4b78ddb2af8325808b83e8a122028623cea96b17b4e8c9e4ee14ea76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
